name: syrius_mobile
version: 0.5.2
publish_to: none
description: Zenon Network Syrius Mobile Wallet

environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  ai_barcode_scanner: ^5.1.1+2
  animate_gradient: ^0.0.3
  app_integrity_checker: ^1.0.5
  app_links: ^6.1.3
  app_settings: ^5.1.1
  argon2_ffi_base: ^1.1.1
  big_decimal: ^0.5.0
  bip39: any
  bitcoin_base: ^4.7.0
  blockchain_utils: ^3.3.0
  cached_network_image: ^3.3.0
  collection: any
  cryptography: ^2.7.0
  dart_bip32_bip44: ^0.2.0
  dotted_border: ^2.1.0
  drift: ^2.20.0
  drift_flutter: ^0.1.0
  eip1559: ^0.6.2
  eth_sig_util: ^0.0.9
  fl_chart: ^0.68.0
  flutter: 
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_localizations: 
    sdk: flutter
  flutter_material_design_icons: ^1.1.7447
  flutter_portal: ^1.1.4
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.1
  flutterlifecyclehooks: ^5.0.0
  font_awesome_flutter: ^10.7.0
  get_it: ^7.2.0
  hex: ^0.2.0
  http: ^1.1.2
  infinite_scroll_pagination: ^4.0.0
  intl: any
  jailbreak_root_detection: ^1.1.1
  json_rpc_2: any
  json_serializable: ^6.8.0
  local_auth: ^2.0.0
  logging: ^1.2.0
  mutex: ^3.1.0
  otp: ^3.1.4
  page_transition: ^2.0.5
  path_provider: ^2.0.9
  pretty_qr_code: ^3.0.0
  provider: ^6.0.2
  retry: ^3.1.2
  rxdart: ^0.28.0
  secp256r1: 
    git: 
      url: https://github.com/drblazer21/flutter_secp256r1/
      ref: fc59b0a4a1b7729a02c86b538e40b39dd9a96e71
  secure_content: ^0.1.0
  share_plus: ^10.0.0
  shared_preferences: ^2.2.3
  skeletonizer: ^1.1.2+1
  svg_path_parser: ^1.1.2
  timer_button: ^2.1.1
  tuple: ^2.0.2
  url_launcher: ^6.0.20
  walletconnect_flutter_v2: ^2.3.1
  web3_provider: ^1.1.4
  web3dart: ^2.7.1
  znn_sdk_dart:
    git:
      url: https://github.com/drblazer21/znn_sdk_dart/
      ref: mobile-support

dev_dependencies: 
  build_runner: ^2.4.12
  dependency_validator: ^4.0.0
  drift_dev: ^2.20.0
  flutter_test: 
    sdk: flutter
  lint: ^2.3.0
  pubspec_dependency_sorter: ^1.0.4

dependency_overrides:
  dart_style: 2.3.6
  web: ^0.5.0

flutter: 
  assets: 
    - assets/images/
    - assets/images/svg/
    - assets/images/svg/icons/
    - assets/images/svg/icons/rewards/
    - assets/images/svg/icons/settings/
    - assets/json/
  fonts:
    - 
      family: Inter
      fonts: 
        - 
          asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100
        - 
          asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - 
          asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - 
          asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - 
          asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - 
          asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - 
          asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - 
          asset: assets/fonts/inter/Inter-Black.ttf
          weight: 800
  uses-material-design: true
  generate: true
