name: Build and release Android APK

on:
  push:
    branches:
      - cicd
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Prepare releases directory
        run: |
          mkdir releases
          
      - name: Set variables
        run: |
          SYRIUS="v$(cat pubspec.yaml | grep version | sed 's/version://' | xargs)"
          echo "Syrius Mobile Version: $SYRIUS"
          echo "SYRIUS_VERSION=$SYRIUS" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Build APK split per ABI
        run: |
          flutter build apk --release --target-platform android-arm64,android-x64 --split-per-abi      

      - name: Build APK universal
        run: |
          flutter build apk --release
      
      - name: Copy to releases directory
        run: |
          cp ./build/app/outputs/flutter-apk/app-arm64-v8a-release.apk ./releases/syrius-mobile-${{ env.SYRIUS_VERSION }}-arm64-v8a-release.apk
          cp ./build/app/outputs/flutter-apk/app-x86_64-release.apk ./releases/syrius-mobile-${{ env.SYRIUS_VERSION }}-x86_64-release.apk
          cp ./build/app/outputs/flutter-apk/app-release.apk ./releases/syrius-mobile-${{ env.SYRIUS_VERSION }}-universal-release.apk

      - name: Generate checksums
        run: |
          cd ./releases
          echo $(sha256sum *)
          echo $(sha256sum *) >> SHA256CHECKSUMS.txt

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: releases/*
          release_name: ${{ env.SYRIUS_VERSION }}
          tag: ${{ env.SYRIUS_VERSION }}-alphanet
          file_glob: true
          overwrite: true
